version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://flaskuser:flaskpassword@db:5432/flaskdb

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
